sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
env:
  global:
  - secure: F9dZyPKN1TGHGKi+VgFFcZxW2i2oN1lZC9D6U7uja/49GzszUF99CNhlvX9x/gRXatRdTEmPl/1YYJIgcQXiWuio33CPKjAab9PJEiXXP1Eo7izVAPsCXBh1+vsomGuSqJCel679jnIIACLEIj0PW2LRUycSPGObX424C9KxDHMG/pOa/+LWwHzY1czh33jbL4gEnSR2/nZqePEHv9XmmnoPGeWcQaXfvUcvWj3FWtaefP4xFXsBLkgfB2Q15jeIuqVx0z9NECBJdYXJktpJRRnkwT8LN5+gFa02MvQ8SUT6P6AlJ5Vg2eexO6C4YfCudML0M0Zh6spE3zCfpCWIXwvDd8zTOmDr3r3CP1NhMr0UQ1dcREEbXb+OKV9AlHKkmwFscgLHvlk3xlz3j9HUuEopQEFyUbYWeViq6OHnv862LWxHSrGd/vN2sY/xZoj9NfV3l5vFP0ECtfvvCf9AGeaJ/f4eKDOSu2GUrDtD5a6cx+ZVrwFUWYYn1JYY2l9jcG7hWcYwdB39yY5zw25Y+ATa2p2r8pF57iFS8+LlrzF3d6yOKGj66liRA1QuLxf8ihBYTtGM8csVyrCe0pt3MyYdQ5xMGNuj9poAiyJx0yonM5y4ShYXoEw2X7ds8tIt+C738EQQ/kzdpPXEeRVzimQsPDPYVXyl+yuZdLQBqU0=
  - FAUNA_DOMAIN=rest.faunadb.com
  - FAUNA_SCHEME=https
  - FAUNA_PORT=443
install:
- pip install coveralls
script:
- coverage run setup.py test
after_success:
- coveralls
notifications:
  email: false
  slack:
    secure: gtLuor9yg9gu5uLm8oOnCuRc7FmGI9Kga/GQjbzRNSVXUiiVZJNoSP03Uq5SwIa3/s5fitiTSObsHowI/VgDNNeLlWT4B0EkvhaNxlQumTYpUUbix7Cd0fLPCkLMGYgNJZ/WJpUFjtDkRbcdgr3Jcj9Dxy7ZpUOgsGRbl/5AXqxHp+zxyFjB0jsFjDpgPpCEzHpllkO9uci1H4ISxt9itLD8rMUjnN+IetX2M3l2982kLLRTSyrGuTNiCNOXMdknSMnygMYnPngF5W9vjZGKz2cv7FGIBvzQQZTAoht0wtZPLgqcQfu+WChMWPE6cwPL2ZKZDE2pPs8kLe8iEtCH3/ozU67gInc8KzcuaevuyE2r4eFHExoq49EYCKxqot5ogUfD0e13O8uMOob+SEpEgiYyySRcOapLac+d84qZQquIyf9SGlWIYOR4jEx7JPBcvHPhlOdRete6G0bZ60qGzyjSe2YpXPF6eM5krw/M7wdkD4AYRD5gqlYu1aSLj+IKg4n56Yjg+wKV2xK5P+QNGF3cuMfQOjqFQ4sivyX0BBQkY6UbAgCG2HmbmmWs1PY2SaDVudLlg1fCaYMWW8/RM00f5uyp0tbpi5TZycmz3hbygyNUwkZmUsOtFsO3I8UF5OTTA6rtr57CRi3WJIZ5Vp1oDUqTexyTDKsEcsFnrGY=
branches:
  only:
    - master
